#!/usr/bin/env python3
"""Generate pa-desktop Tauri icons: a minimal rounded-square "PA" mark."""
from PIL import Image, ImageDraw, ImageFont
import os

OUT = "/home/ubuntu/pa-desktop/app/src-tauri/icons"
os.makedirs(OUT, exist_ok=True)

def make(size, name, transparent=False, icns_style=False):
    s = size
    img = Image.new("RGBA", (s, s), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    # dark rounded square background (Unsloth-minimal vibe)
    pad = s * 0.06
    radius = s * 0.22
    d.rounded_rectangle([pad, pad, s - pad, s - pad], radius=radius,
                        fill=(16, 18, 24, 255))
    # accent bar
    d.rounded_rectangle([s*0.30, s*0.28, s*0.70, s*0.32], radius=radius,
                        fill=(120, 140, 255, 255))
    d.rounded_rectangle([s*0.30, s*0.52, s*0.70, s*0.56], radius=radius,
                        fill=(120, 140, 255, 255))
    # "PA" glyph
    try:
        font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", int(s*0.30))
    except Exception:
        font = ImageFont.load_default()
    d.text((s*0.32, s*0.60), "PA", font=font, fill=(235, 238, 255, 255))
    img.save(os.path.join(OUT, name))

make(32, "32x32.png")
make(128, "128x128.png")
make(256, "128x128@2x.png")

# Windows .ico (multi-size)
from PIL import Image as I
ico_sizes = [16, 24, 32, 48, 64, 128, 256]
imgs = []
for sz in ico_sizes:
    im = Image.new("RGBA", (sz, sz), (0, 0, 0, 0))
    dd = ImageDraw.Draw(im)
    pad = sz * 0.06; radius = sz * 0.22
    dd.rounded_rectangle([pad, pad, sz-pad, sz-pad], radius=radius, fill=(16,18,24,255))
    dd.rounded_rectangle([sz*0.30, sz*0.28, sz*0.70, sz*0.32], radius=radius, fill=(120,140,255,255))
    dd.rounded_rectangle([sz*0.30, sz*0.52, sz*0.70, sz*0.56], radius=radius, fill=(120,140,255,255))
    try:
        font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", int(sz*0.30))
    except Exception:
        font = ImageFont.load_default()
    dd.text((sz*0.32, sz*0.60), "PA", font=font, fill=(235,238,255,255))
    imgs.append(im)
imgs[-1].save(os.path.join(OUT, "icon.ico"), format="ICO", sizes=[(s, s) for s in ico_sizes])

# macOS .icns (512 + 256 as PNG-in-icns; PIL cannot author real icns, so we
# ship a 512 PNG named icon.icns placeholder — Tauri accepts PNG bytes for icns
# on non-mac builds; real icns is generated by `tauri icon` on macOS).
for sz, nm in [(512, "icon.icns")]:
    im = Image.new("RGBA", (sz, sz), (0, 0, 0, 0))
    dd = ImageDraw.Draw(im)
    pad = sz * 0.06; radius = sz * 0.22
    dd.rounded_rectangle([pad, pad, sz-pad, sz-pad], radius=radius, fill=(16,18,24,255))
    dd.rounded_rectangle([sz*0.30, sz*0.28, sz*0.70, sz*0.32], radius=radius, fill=(120,140,255,255))
    dd.rounded_rectangle([sz*0.30, sz*0.52, sz*0.70, sz*0.56], radius=radius, fill=(120,140,255,255))
    try:
        font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", int(sz*0.30))
    except Exception:
        font = ImageFont.load_default()
    dd.text((sz*0.32, sz*0.60), "PA", font=font, fill=(235,238,255,255))
    im.save(os.path.join(OUT, nm))

print("icons written:", sorted(os.listdir(OUT)))
